# Generated by Django 5.2.5 on 2025-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.PositiveIntegerField(default=70563, verbose_name='House number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default=1, max_length=120, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postcode/PLZ'),
        ),
    ]
