# Generated by Django 5.2.5 on 2025-08-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('view_fulfillment', 'Can access fulfillment (paid picklists)')]},
        ),
    ]
