# Generated by Django 5.2.5 on 2025-08-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fulfilled_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('view_fulfillment', 'Can access fulfillment (paid picklists)'), ('change_fulfillment_status', 'Can mark orders fulfilled')]},
        ),
    ]
