# Generated by Django 5.2.5 on 2025-08-29 18:51
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_options"),
    ]

    operations = [
        # Rename existing columns so data is preserved
        migrations.RenameField(
            model_name="order",
            old_name="address_line1",
            new_name="street",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="address_line2",
            new_name="house_number",
        ),

        # Adjust types/constraints if needed
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="order",
            name="house_number",
            field=models.CharField(max_length=10, blank=True),
        ),
    ]
